# Generated by Django 6.0.5 on 2026-05-28 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedEmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('activity_date', models.DateField()),
                ('activity_value', models.FloatField()),
                ('original_unit', models.CharField(max_length=50)),
                ('normalized_unit', models.CharField(max_length=50)),
                ('emission_factor', models.FloatField()),
                ('co2e_emission', models.FloatField()),
                ('validation_flags', models.JSONField(default=list)),
                ('review_status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=50)),
                ('locked_for_audit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('raw_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.rawrecord')),
            ],
        ),
    ]
